# Generated by Django 3.2.6 on 2021-09-13 06:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_added_is_oauth'),
        ('workspaces', '0001_created_workspace_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='WorkspaceMember',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.user')),
                ('workspace_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='workspaces.workspace')),
            ],
            options={
                'db_table': '"workspace_members"',
            },
        ),
    ]
