# Generated by Django 3.2.6 on 2021-09-13 22:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_fixed_workspace_member_field_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceMemberQueue',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=1000)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='workspaces.workspace')),
            ],
            options={
                'db_table': '"workspace_member_queues"',
            },
        ),
    ]
