# Generated by Django 3.2.6 on 2021-09-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_fix_workspace_on_delete_cascade'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacememberqueue',
            name='is_pending_join',
            field=models.BooleanField(default=False),
        ),
    ]
