# Generated by Django 3.2.6 on 2021-09-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0006_added_is_pending_join'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacememberqueue',
            name='token',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
