# Generated by Django 3.2.6 on 2021-09-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0007_set_member_queue_token_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspacemember',
            name='member',
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='status',
            field=models.IntegerField(choices=[(1, 'Invited'), (2, 'Pending'), (3, 'Joined')], default=1),
        ),
        migrations.DeleteModel(
            name='WorkspaceMemberQueue',
        ),
    ]
