# Generated by Django 3.2.6 on 2021-09-28 07:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0009_added_email_in_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('workspace_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace')),
            ],
            options={
                'db_table': '"folders"',
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('folder_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.folder')),
            ],
            options={
                'db_table': '"lists"',
            },
        ),
        migrations.CreateModel(
            name='FolderList',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('folder_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.folder')),
                ('list_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.list')),
            ],
            options={
                'db_table': '"folder_lists"',
            },
        ),
    ]
