# Generated by Django 3.2.6 on 2021-10-01 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0010_added_folder_and_list_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FolderList',
        ),
    ]
