# Generated by Django 3.2.6 on 2021-10-01 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0011_deleted_folder_list_conjunction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1)),
                ('status', models.IntegerField(choices=[(1, 'Todo'), (2, 'In Progress'), (3, 'In Review'), (4, 'In Evaluation'), (5, 'Done')], default=1)),
                ('list_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.list')),
            ],
            options={
                'db_table': '"stories"',
            },
        ),
    ]
