# Generated by Django 3.2.6 on 2021-10-02 17:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0016_task_assignees_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('is_done', models.BooleanField(default=False, editable=False)),
                ('assignee_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.taskassignee')),
                ('task_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.task')),
            ],
            options={
                'db_table': '"subtasks"',
            },
        ),
    ]
