# Generated by Django 3.2.6 on 2021-10-02 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0017_subtask_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='assignee_uuid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workspaces.taskassignee'),
        ),
    ]
