# Generated by Django 3.2.6 on 2022-01-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0018_subtask_assignee_null_true'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='name',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
