# Generated by Django 3.2.6 on 2022-01-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0019_story_name_to_80_max_len'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
