# Generated by Django 3.2.6 on 2021-09-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authentications',
            fields=[
                ('refresh_token', models.CharField(max_length=1000, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': '"authentications"',
            },
        ),
    ]
